In [ ]:
import numpy as np

In [ ]:
array = np.array([5,12,5,6,3,4, 5, 6, 4, 5,1, 3])

In [ ]:
print(array.sum())
print(array.mean())
print(array.std())
print(array.min())
print(array.max())


35
5.833333333333333
2.91070819942883
3
12


In [ ]:
array = array.reshape(4,3)
print(array)
print(array.mean(axis=0))
print(array.std(axis = 1))

[[ 5 12  5]
 [ 6  3  4]
 [ 5  6  4]
 [ 5  1  3]]
[5.25 5.5  4.  ]
[3.29983165 1.24721913 0.81649658 1.63299316]


In [ ]:
rng = np.random.default_rng(42)
print(rng.random(6)*10)
print(rng.integers(10, size = 10))
deck = np.arange(52)
print(rng.permutation(deck))

[7.73956049 4.3887844  8.5859792  6.97368029 0.94177348 9.75622352]
[7 7 7 7 5 1 8 4 5 3]
[48 28 18 25 39 37  0 49 33 29 22 45 44 17  4 24 21  7 26 12  8 46 36  5
  1 27 50  2 40 11 14 20 19 32 42 23 41 15  9 31 43 16 51  3 34 30 10 35
 13  6 38 47]


In [ ]:
X = rng.integers(0, 10, (4, 4))
print(X)

np.sum(X, axis=0)
np.sum(X, axis=1)

[[7 3 6 0]
 [3 4 9 2]
 [2 4 9 8]
 [0 2 8 0]]


array([16, 18, 23, 10])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = [1,3,4,5,6]
myseries = pd.Series(a)
print(myseries)

0    1
1    3
2    4
3    5
4    6
dtype: int64


In [ ]:
b = [1, 2, 3]
myseries = pd.Series(b, index = ['a','b','c'])
print(myseries)

a    1
b    2
c    3
dtype: int64


In [ ]:
print(myseries['b'])

2


In [ ]:
grades = {"adam": 85, "betty":90, "caroline": 50}
myseries = pd.Series(grades)
print(myseries)

adam        85
betty       90
caroline    50
dtype: int64


In [ ]:
data = {
    "name": ["adam", "betty", "caroline"],
    "grade": [85, 90, 50]
}
mytable = pd.DataFrame(data)
print(mytable)

       name  grade
0      adam     85
1     betty     90
2  caroline     50


In [ ]:
mytable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   grade   3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [ ]:
mytable.describe(include='all')

name      grade
count      3   3.000000
unique     3        NaN
top     adam        NaN
freq       1        NaN
mean     NaN  75.000000
std      NaN  21.794495
min      NaN  50.000000
25%      NaN  67.500000
50%      NaN  85.000000
75%      NaN  87.500000
max      NaN  90.000000

In [ ]:
print(mytable.iloc[0])
print(mytable.loc[0,'grade'])
print(mytable.loc[2,'name'])
print(mytable.loc[0:2,'name'])
print(mytable.iloc[0:2])

print(mytable[mytable['grade'] > 70])

name     adam
grade      85
Name: 0, dtype: object
85
caroline
0        adam
1       betty
2    caroline
Name: name, dtype: object
    name  grade
0   adam     85
1  betty     90
    name  grade
0   adam     85
1  betty     90


In [ ]:
dataframe = pd.read_csv('/content/personality_datasert.csv')

In [ ]:
print(dataframe)

      Time_spent_Alone Stage_fear  Social_event_attendance  Going_outside  \
0                  4.0         No                      4.0            6.0   
1                  9.0        Yes                      0.0            0.0   
2                  9.0        Yes                      1.0            2.0   
3                  0.0         No                      6.0            7.0   
4                  3.0         No                      9.0            4.0   
...                ...        ...                      ...            ...   
2895               3.0         No                      7.0            6.0   
2896               3.0         No                      8.0            3.0   
2897               4.0        Yes                      1.0            1.0   
2898              11.0        Yes                      1.0            3.0   
2899               3.0         No                      6.0            6.0   

     Drained_after_socializing  Friends_circle_size  Post_frequency  \
0   

In [ ]:
print(dataframe.iloc[0])

Time_spent_Alone                   4.0
Stage_fear                          No
Social_event_attendance            4.0
Going_outside                      6.0
Drained_after_socializing           No
Friends_circle_size               13.0
Post_frequency                     5.0
Personality                  Extrovert
Name: 0, dtype: object


In [ ]:
x = np.arange(10)
np.save('x.npy',x)
y = np.load('x.npy')