Numpy

In [1]:
!pip install numpy

In [2]:
import numpy

In [15]:
numbers = [1,2,3,4,5]
array = numpy.array(numbers)
print(array)

array = numpy.array([1,2,3,4,5,6])
print(array)

array = numpy.array((1,2,5,3,4))
print(array)

array = [n for n in range(1,10) if n%2 == 0]
print(array)

array2 = numpy.arange(1,10, 2)
print(array2)

zeros = numpy.zeros(26)
print(zeros)



[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 5 3 4]
[2, 4, 6, 8]
[1 3 5 7 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


1 2 3 4
3 4 5 6

In [24]:
twod = [[1,2,3],[1,5,4]]
"""
1 2 3
1 5 4
"""
"""
1 2 3 4
3 4 5 6
"""
numpyd = numpy.array(twod)

print(numpyd[1][1])

threed = numpy.array([[[1,3], [5,4], [3,5]],[[1,3], [5,4], [3,5]]] )
print(threed)
print(threed.ndim)
array = numpy.array([1,2,3,4,1,4], ndmin = 4)
print(array)
print(array.ndim)



5
[[[1 3]
  [5 4]
  [3 5]]

 [[1 3]
  [5 4]
  [3 5]]]
3
[[[[1 2 3 4 1 4]]]]
4


In [33]:
twod = [[1,2,3,1,3,4],[1,5,4,1,4,4]]
print(twod[1][-1])
print(twod[0][:3])
print(twod[:1][:3])

print(twod[0][0:5:2])

twod = numpy.array(twod)

print(twod.shape)
print(numpy.shape(twod))
print(threed.shape)

4
[1, 2, 3]
[[1, 2, 3, 1, 3, 4]]
[1, 3, 3]
(2, 6)
(2, 6)
(2, 3, 2)


In [42]:
"""
newtwod = twod.reshape(6,2)
print(newtwod)
print(newtwod.shape)

newtwod = twod.reshape(3,4)
print(newtwod)
print(newtwod.shape)

#newtwod = twod.reshape(3,5)

newtwod = twod.reshape(3,2,2)
print(newtwod)
print(newtwod.shape)

newtwod = twod.reshape(3, -1)
print(newtwod)
print(newtwod.shape)

twod = numpy.arange(20).reshape(4,5)
print(twod)
"""
threed = twod.reshape(5,2,2)
print(threed)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [46]:
newtwod = twod.copy()
newtwod[0][0] = 200
print(newtwod)
print(twod)


[[200   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [59]:
x = numpy.array([1,2,3])
y = numpy.array([4,5,6])
threed1 = numpy.array([[[1,3], [5,4], [3,5]],[[1,3], [5,4], [3,5]]] )
threed2 = numpy.array([[[1,3], [5,4], [3,5]],[[1,3], [5,4], [3,5]]] )

c = numpy.concatenate((x,y))
"""
print(c)
v = numpy.vstack((x,y))
print(v)
h = numpy.hstack((x,y))
print(h)
threed3 = numpy.hstack((threed1, threed2))
print(threed3)
print(threed3.shape)
threed3 = numpy.vstack((threed1, threed2))
print(threed3)
print(threed3.shape)
"""

c2 = numpy.concatenate((threed1, threed2), axis = 2)
print(c2)
print(c2.shape)

twod = numpy.array([[1,2,3,1,3,4],[1,5,4,1,4,4]])
twod2 = numpy.array([[1,2,3,1,3,4],[1,5,4,1,4,4]])

twod3 = numpy.hstack((twod, twod2))
print(twod3)
print(twod3.shape)

(2, 3)
twod3 = numpy.concatenate((twod,twod2), axis = -1)
print(twod3)
print(twod3.shape)




[[[1 3 1 3]
  [5 4 5 4]
  [3 5 3 5]]

 [[1 3 1 3]
  [5 4 5 4]
  [3 5 3 5]]]
(2, 3, 4)
[[1 2 3 1 3 4 1 2 3 1 3 4]
 [1 5 4 1 4 4 1 5 4 1 4 4]]
(2, 12)
[[1 2 3 1 3 4]
 [1 5 4 1 4 4]
 [1 2 3 1 3 4]
 [1 5 4 1 4 4]]
(4, 6)


In [67]:
long = numpy.arange(100)
smaller = numpy.array(numpy.array_split(long,4))
print(smaller)
print(smaller.shape)
print(smaller[0])
long2d = numpy.arange(100).reshape(2, 50)

smaller2d = numpy.array(numpy.array_split(long2d, 2))
print(smaller2d)
print(smaller2d.shape)


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
(4, 25)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
   46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
   96 97 98 99]]]
(2, 1, 50)


In [69]:
array = numpy.array([1,6,2,8,1,5,4])
print(numpy.sort(array))

[1 1 2 4 5 6 8]


In [75]:
twod = numpy.array([[1,-2,3,-1,3,4],[1,5,-4,1,4,-4]])
print(numpy.sort(twod))

print(numpy.where(twod < 0))
print(numpy.where(twod %3 == 0))

[[-2 -1  1  3  3  4]
 [-4 -4  1  1  4  5]]
(array([0, 0, 1, 1]), array([1, 3, 2, 5]))
(array([0, 0]), array([2, 4]))


In [78]:
twod = numpy.array([[1,-2,3,-1,3,4],[1,5,-4,1,4,-4]])

filter = twod < 0

newarr = twod[filter]
print(newarr)
array = numpy.array([ 1, 5, 3, 10])
filter = [False, True, False, False]
newarr = array[filter]
print(newarr)



[-2 -1 -4 -4]
[5]
